import { z } from "zod";

export const UploadSubtitlesRequestSchema = z.object({
  contentId: z.string(),
  language: z.string(),
  isDefault: z.boolean().optional(),
  isAutoGenerated: z.boolean().optional(),
});
export type UploadSubtitlesRequest = z.infer<typeof UploadSubtitlesRequestSchema>;
