import { z } from "zod";

export const SubtitleDtoSchema = z.object({
  id: z.string(),
  language: z.string(),
  url: z.string(),
  isDefault: z.boolean(),
  isAutoGenerated: z.boolean(),
});
export type SubtitleDto = z.infer<typeof SubtitleDtoSchema>;
